[package]
name = "tg-browser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
url.workspace = true
tg-core = { path = "../tg-core" }
tg-network = { path = "../tg-network" }
tg-terminal = { path = "../tg-terminal" }

[dev-dependencies]
futures-util.workspace = true
serde.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true

[lints]
workspace = true
